# R8 / ProGuard rules for release builds.

# slf4j ships an optional static logger binder (org.slf4j.impl.StaticLoggerBinder)
# that is only present when an slf4j backend is on the classpath. This app has
# no such backend, so the reference is never used at runtime. Suppress the R8
# "Missing class" error for it (rule generated by AGP in missing_rules.txt).
-dontwarn org.slf4j.**
